import random

__palabras=[

'AUTO','LANCHA','CRUZERO','MOTOCICLETA','BICICLETA','TRICICLO',
'METRO','BUS','CAMION','TREN','TRANVIA','TAXI','BARCO',

'CASCO','WINCHA','CEMENTO','PIEDRA','ARENA','CLAVOS',
'MADERA','TUBERIA','MARTILLO','LAMPA','PICO','ANDAMIO',
'CORTADORA','PULIDORA','DRYWALL','CARRETILLA','LADRILLO','BLOQUETA',

'CARNICERO','CONDUCTOR','MAESTRA','DOCTORA','INGENIERO','ABOGADO','JUEZ',
'POLITICO','ORADOR','VERDULERO','COMERCIANTE','PILOTO','ENFERMERA','ESTUDIANTE',

'MERCADO','OFICINA','ESCUELA','COLEGIO','HOSPITAL','TALLER','FABRICA',
'TIENDA','AEROPUERTO','TERRAPUERTO','CARRETERA','AUTOPISTA','VEREDA','PARQUE',
'PLAZA','PUENTE','COMISARIA','CARCEL','RESTAURANTE','UNIVERSIDAD','BARRIO',

'PERU','CHILE','COLOMBIA','ECUADOR','BRASIL','ARGENTINA',
'MEXICO','CUBA','ESPAÑA','PORTUGAL','JAMAICA','RUSIA',
'CHINA','JAPON','RUSIA','INDIA','MONGOLIA','COREA',

'AMERICA','EUROPA','AFRICA','ASIA','OCEANIA','SOL',
'LUNA','MERCURIO','VENUS','TIERRA','MARTE','JUPITER',
'SATURNO','URANO','NEPTUNO','PLUTON','QUASAR','COMETA',
'ASTEROIDE','ESTRELLA','CUMULO','GALAXIA','ATRACTOR','BIGBANG',

'CABALLO','VACA','PINGUINO','GAVIOTA','PERRO','GATO','GAVIOTA',
'PALOMA','LEON','ELEFANTE','JIRAFA','JABALI','CEBRA',
'OSO','ARAÑA','GUSANO','CANGREJO','TIBURON','PULPO'

'TOMATE','MAIZ','PAPA','TRIGO','CEBADA','ARROZ','LENTEJAS',
'CARNE','POLLO','HUEVOS','COLIFLOR','ALCACHOFA','SANDIA',
'MANGO','PLATANO','MANZANA','NARANJA','PAN','LIMON',
'CEBOLLA','ZANAHORIA','QUESO','PESCADO','FIDEO','ACEITE'

'ROJO','AZUL','AMARILLO','VERDE','BLANCO','NEGRO',
'CELESTE','MORADO','GRIS','CREMA','VIOLETA','DORADO',

'MATEMATICA','FISICA','QUIMICA','FILOSOFIA','MEDICINA','SOCIOLOGIA',
'PSICOLOGIA','ESTADISTICA','AERONAUTICA','HIDRAULICA','ESTATICA','DINAMICA',
'HIDROLOGIA','TOPOGRAFIA','GEOGRAFIA','GEODESIA','CONSTRUCCION','ESTRUCTURAS',
'INSTALCIONES','ELECTRONICA','PROGRAMACION','ECONOMIA','PRESUPUESTOS','PRACTICA'
]

def ObtenerPalabra():
	return(random.choice(__palabras))
